 # Pandas


Pandas 데이터 프레임의 장점
- **구조화된 데이터를 효과적으로 처리하고 저장**
- 대용량 데이터를 빠르고 쉽게 다를 수 있다 (한계용량: 엑셀 약 100MB, Pandas DataFrame 1GB~ 100GB)
- 복잡한 기능을 구현하기 쉽다
- 데이터 전처리를 쉽게 할 수 있다
- 다른 시스템(웹 개발, 데이터베이스, 머신러닝 등)과 연동이 쉽다
- Numpy 라이브러리에서 지원하는 수학 및 통계 연산을 그대로 이용할 수 있다. (Numpy를 기반으로 설계했기 때문에!)
- excel, csv 파일을 읽고, 저장할 수 있다.

학습목표
  * *pandas* 라이브러리의 `DataFrame` 및 `Series` 데이터 구조에 학습하기
  * `DataFrame` 및 `Series` 내의 데이터 액세스 및 조작
  *  *pandas* 연산과 함수, 정렬하기
  * *pandas* `DataFrame`으로 csv 등의 데이터 가져오기
  * `DataFrame` 조건으로 검색하기
  * `DataFrame` 함수로 데이터 처리하기
  * `DataFrame` 그룹으로 묶기
  * 멀티인덱스와 피봇테이블

## Pandas 조건으로 검색하기

Pandas는 Numpy와 마찬가지로 마스킹 연산이 가능합니다.   
즉, 조건에 맞는 DataFrame row를 추출하는 것이 가능합니다.

In [141]:
# Numpy Masking
import numpy as np

array1 = np.arange(16).reshape(4, 4)
print(array1)
print("\n--------------\n")
array2 = array1 < 10
print(array2)
print("\n--------------\n")

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

--------------

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]

--------------

[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [142]:
import pandas as pd
ArbNight = [['알라딘', 26, '무직', '아라비아'],
            ['자스민', 25, '공주', '아라비아'],
            ['지니', 3000, '요정', '아라비아'],
            ['자파', 50, '악당', '아라비아']]

cols = ['name', 'age', 'job', 'country']

df = pd.DataFrame(ArbNight, columns=cols)
df

name   age job country
0  알라딘    26  무직    아라비아
1  자스민    25  공주    아라비아
2   지니  3000  요정    아라비아
3   자파    50  악당    아라비아

In [143]:
'알라딘' in df

False

In [144]:
'알라딘' in df['name']

False

In [145]:
'알라딘' in list(df['name'])

True

In [146]:
'알라딘' in df['name'].values

True

In [147]:
df['name']=='자파'

0    False
1    False
2    False
3     True
Name: name, dtype: bool

나이가 30세 이하인 행만 뽑고 싶다면

In [148]:
# 나이가 30세 이하 => df['age'] <= 30 => return이 True인 행만
# df[ << 조건식 >> ] => << 조건식 >> 리턴값이 True인 행만 뽑는다.
df[df['age'] <= 30]

name  age job country
0  알라딘   26  무직    아라비아
1  자스민   25  공주    아라비아

In [149]:
df['age'] <= 30

0     True
1     True
2    False
3    False
Name: age, dtype: bool

In [150]:
df['name']=='지니'

0    False
1    False
2     True
3    False
Name: name, dtype: bool

In [151]:
df[df['name']=='지니']

name   age job country
2   지니  3000  요정    아라비아

Quiz. df에서 알라딘과 자스민만 뽑아보세요.

In [152]:
# 직접 풀어보세요

df[df['name'].isin(['알라딘', '자스민'])]

name  age job country
0  알라딘   26  무직    아라비아
1  자스민   25  공주    아라비아

In [153]:
#@title
df[(df['name']=='알라딘' ) | (df['name'] == '자스민')]

name  age job country
0  알라딘   26  무직    아라비아
1  자스민   25  공주    아라비아

In [154]:
#@title
df[df['name'].isin(['알라딘', '자스민'])]

name  age job country
0  알라딘   26  무직    아라비아
1  자스민   25  공주    아라비아

In [155]:
# 딕셔너리 형태로 데이터프레임 만들기
table2 = {
    '일자':['2021-12-06','2021-12-07','2021-12-08','2021-12-09'],
    '가격':[1000,3000,2000,1000],
    '구매여부':[False, True, True, True],
    '제품': ['gum','snack','beverage','gum']
}

df2 = pd.DataFrame(table2)
df2

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

문제. 제품이 'gum'이나 'snack'이 아닌 것을 출력하세요

In [156]:
# 직접 풀어보세요

df2[(df2['제품'] != 'gum') & (df2['제품'] != 'snack')]

일자    가격  구매여부        제품
2  2021-12-08  2000  True  beverage

In [157]:
#@title
df2[(df2['제품'] != 'gum') & (df2['제품'] != 'snack')]

일자    가격  구매여부        제품
2  2021-12-08  2000  True  beverage

In [158]:
#@title
data = ['gum','snack']

df2[~df2['제품'].isin(data)]

일자    가격  구매여부        제품
2  2021-12-08  2000  True  beverage

In [159]:
# 특정 조건에 따른 데이터 생성
condition1 = (df2['제품'] == 'gum') & (df2['구매여부'] == False)

df2.loc[condition1, '관심대상'] = True
df2.loc[~condition1, '관심대상'] = False
df2

일자    가격   구매여부        제품   관심대상
0  2021-12-06  1000  False       gum   True
1  2021-12-07  3000   True     snack  False
2  2021-12-08  2000   True  beverage  False
3  2021-12-09  1000   True       gum  False

#### 문제. 컬럼 "구매여부_2"를 생성하세요
    - 구매여부 False -> "No"
    - 구매여부 True -> "Yes"

In [160]:
# 직접 풀어보세요





In [161]:
#@title
df2.loc[df2['구매여부']==True, '구매여부_2'] = 'Yes'
df2.loc[df2['구매여부']==False, '구매여부_2'] = 'No'
df2

일자    가격   구매여부        제품   관심대상 구매여부_2
0  2021-12-06  1000  False       gum   True     No
1  2021-12-07  3000   True     snack  False    Yes
2  2021-12-08  2000   True  beverage  False    Yes
3  2021-12-09  1000   True       gum  False    Yes

In [162]:
#@title
df2.loc[df2['구매여부'], '구매여부_2'] = 'Yes'
df2.loc[~df2['구매여부'], '구매여부_2'] = 'No'
df2

일자    가격   구매여부        제품   관심대상 구매여부_2
0  2021-12-06  1000  False       gum   True     No
1  2021-12-07  3000   True     snack  False    Yes
2  2021-12-08  2000   True  beverage  False    Yes
3  2021-12-09  1000   True       gum  False    Yes

###query

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html

In [163]:
# query를 이용한 선택
df2.query('가격 > 2000')

일자    가격  구매여부     제품   관심대상 구매여부_2
1  2021-12-07  3000  True  snack  False    Yes

In [164]:
df2.query('가격 >= 2000 & 제품 == "snack"')

일자    가격  구매여부     제품   관심대상 구매여부_2
1  2021-12-07  3000  True  snack  False    Yes

In [165]:
df2.query('가격 >= 2000 | 구매여부 == "True"')

일자    가격  구매여부        제품   관심대상 구매여부_2
1  2021-12-07  3000  True     snack  False    Yes
2  2021-12-08  2000  True  beverage  False    Yes

In [166]:
df2[(df2['가격'] >= 2000) | (df2['제품'] == "snack")]

일자    가격  구매여부        제품   관심대상 구매여부_2
1  2021-12-07  3000  True     snack  False    Yes
2  2021-12-08  2000  True  beverage  False    Yes

In [167]:
# 샘플 데이터 다운로드
import seaborn as sns
df_tips = sns.load_dataset("tips")
df_tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

문제. 금요일 Non smoker의 tip 목록을 출력하세요

In [168]:
# 직접 풀어보세요

df_tips[(df_tips['day']=='Fri') & (df_tips['smoker']=='No')]

total_bill   tip     sex smoker  day    time  size
91        22.49  3.50    Male     No  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
99        12.46  1.50    Male     No  Fri  Dinner     2
223       15.98  3.00  Female     No  Fri   Lunch     3

In [169]:
#@title
df_tips.query("smoker=='No' & day == 'Fri'")

total_bill   tip     sex smoker  day    time  size
91        22.49  3.50    Male     No  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
99        12.46  1.50    Male     No  Fri  Dinner     2
223       15.98  3.00  Female     No  Fri   Lunch     3

In [170]:
df_tips.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

## 함수로 데이터 처리하기

In [171]:
import numpy as np
df = pd.DataFrame(np.arange(1,10).reshape(3,3))
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [172]:
# apply
df.apply(np.median, axis=1)

0    2.0
1    5.0
2    8.0
dtype: float64

In [173]:
df.apply(np.median, axis=0)

0    4.0
1    5.0
2    6.0
dtype: float64

In [174]:
df = pd.DataFrame(np.arange(5), columns=["Num"])
df

Num
0    0
1    1
2    2
3    3
4    4

In [175]:
def square(x):
    return x**2

df["Square_1"] = df['Num'].apply(square)
df

Num  Square_1
0    0         0
1    1         1
2    2         4
3    3         9
4    4        16

In [176]:
df["Square_2"] = df.Num.apply(lambda x: x ** 2)
df

Num  Square_1  Square_2
0    0         0         0
1    1         1         1
2    2         4         4
3    3         9         9
4    4        16        16

In [177]:
df = pd.DataFrame(columns=["phone"])
df.loc[0] = "010-1234-1235"
df.loc[1] = "공일공-일이삼사-1235"
df.loc[2] = "010.1234.일이삼오"
df.loc[3] = "공1공-1234.1이3오"

df["preprocess_phone"] = ''
df

phone preprocess_phone
0  010-1234-1235                 
1  공일공-일이삼사-1235                 
2  010.1234.일이삼오                 
3  공1공-1234.1이3오

In [178]:
def get_preprocess_phone(phone):
    mapping_dict = {
    "공": "0",
    "일": "1",
    "이": "2",
    "삼": "3",
    "사": "4",
    "오": "5",
    "-": "",
    ".": "",
    }
    for key, value in mapping_dict.items():
        phone = phone.replace(key, value)
    return phone

df["preprocess_phone"] = df["phone"].apply(get_preprocess_phone)
df

phone preprocess_phone
0  010-1234-1235      01012341235
1  공일공-일이삼사-1235      01012341235
2  010.1234.일이삼오      01012341235
3  공1공-1234.1이3오      01012341235

문제. 아래 표처럼 중간 4자리를 *표로 바꿔보세요

In [179]:
# 직접 해보세요
# df["masked_data"] =

In [180]:
#@title
df['masked_data'] = df['preprocess_phone'].apply(lambda x : x[:3] +'*'*(len(x)-7) + x[-4:])
df

phone preprocess_phone  masked_data
0  010-1234-1235      01012341235  010****1235
1  공일공-일이삼사-1235      01012341235  010****1235
2  010.1234.일이삼오      01012341235  010****1235
3  공1공-1234.1이3오      01012341235  010****1235

In [181]:
# 딕셔너리 형태로 데이터프레임 만들기
table2 = {
    '일자':['2021-12-06','2021-12-07','2021-12-08','2021-12-09'],
    '가격':[1000,3000,2000,1000],
    '구매여부':['False','True','True','True'],
    '제품': ['gum','snack','beverage','gum']
}

df2 = pd.DataFrame(table2)
df2

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

#### mapping

In [182]:
df2['구매여부(replace)'] = df2['구매여부'].replace('True', 0).replace('False', 1)
df2

/tmp/ipython-input-388968777.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['구매여부(replace)'] = df2['구매여부'].replace('True', 0).replace('False', 1)


일자    가격   구매여부        제품  구매여부(replace)
0  2021-12-06  1000  False       gum              1
1  2021-12-07  3000   True     snack              0
2  2021-12-08  2000   True  beverage              0
3  2021-12-09  1000   True       gum              0

In [183]:
# 한글말로 수정
df2['제품(replace)'] = df2['제품'].replace('gum', '껌').replace('snack', '과자').replace('beverage','음료')
df2

일자    가격   구매여부        제품  구매여부(replace) 제품(replace)
0  2021-12-06  1000  False       gum              1           껌
1  2021-12-07  3000   True     snack              0          과자
2  2021-12-08  2000   True  beverage              0          음료
3  2021-12-09  1000   True       gum              0           껌

In [184]:
# 딕셔너리로 맵핑하기
mapping = {'gum': '껌', 'snack':'과자', 'beverage':'음료'}

df2['제품(replace)_ver2'] = df2['제품'].map(mapping)
df2

일자    가격   구매여부        제품  구매여부(replace) 제품(replace)  \
0  2021-12-06  1000  False       gum              1           껌   
1  2021-12-07  3000   True     snack              0          과자   
2  2021-12-08  2000   True  beverage              0          음료   
3  2021-12-09  1000   True       gum              0           껌   

  제품(replace)_ver2  
0                껌  
1               과자  
2               음료  
3                껌

### 연습

In [185]:
# 샘플 데이터 다운로드
import pandas as pd
import seaborn as sns
df_tips = sns.load_dataset("tips")
df_tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

문제1. `total_bill`을 `size`로 나눈 값을 `bill_per_size` 컬럼으로 만드세요.

In [186]:
# 직접 풀어보세요

df_tips['bill_per_size'] = df_tips['total_bill'] / df_tips['size']
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000

[244 rows x 8 columns]

In [187]:
#@title
df_tips['bill_per_size'] = df_tips.apply(lambda x : x['total_bill'] / x['size'], axis=1)
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000

[244 rows x 8 columns]

문제2. `percentage` 컬럼을 만드세요.
- 소숫점 2째 자리에서 반올림하세요
- 00.00 % 문자열 형식으로 표현하세요
    
$$ \frac{tip}{totalbill} * 100 $$

In [188]:
# 직접 풀어보세요

df_tips['percentage'] = df_tips.apply(lambda x : f"{x['tip'] / x['total_bill'] * 100:.2f}%", axis=1)
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

    percentage  
0        5.94%  
1       16.05%  
2       16.66%  
3       13.98%  
4       14.68%  
..         ...  
239     20.39%  
240      7.36%  
241      8.82%  
242      9.82%  
243     15.97%  

[244 rows x 9 columns]

In [189]:
#@title
df_tips['percentage'] = round(df_tips.tip / df_tips.total_bill * 100, 2).astype(str) + "%"
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

    percentage  
0        5.94%  
1       16.05%  
2       16.66%  
3       13.98%  
4       14.68%  
..         ...  
239     20.39%  
240      7.36%  
241      8.82%  
242      9.82%  
243     15.97%  

[244 rows x 9 columns]

In [190]:
#@title
df_tips['percentage'] = df_tips.apply(lambda x : "{:.2f}%".format(x.tip / x.total_bill * 100) , axis=1)
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

    percentage  
0        5.94%  
1       16.05%  
2       16.66%  
3       13.98%  
4       14.68%  
..         ...  
239     20.39%  
240      7.36%  
241      8.82%  
242      9.82%  
243     15.97%  

[244 rows x 9 columns]

In [191]:
#@title
df_tips['percentage'] = df_tips.apply(lambda x : str(round(x.tip / x.total_bill * 100,2)) + "%" , axis=1)
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

    percentage  
0        5.94%  
1       16.05%  
2       16.66%  
3       13.98%  
4       14.68%  
..         ...  
239     20.39%  
240      7.36%  
241      8.82%  
242      9.82%  
243     15.97%  

[244 rows x 9 columns]

문제3. Dinner를 저녁, Lunch를 점심으로 바꾸어 `시간대` column으로 저장하세요

In [192]:
# 직접 풀어보세요


In [193]:
#@title
dic_time = {"Dinner" : "저녁", "Lunch" : "점심"}
df_tips['시간대'] = df_tips['time'].map(dic_time)
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

    percentage 시간대  
0        5.94%  저녁  
1       16.05%  저녁  
2       16.66%  저녁  
3       13.98%  저녁  
4       14.68%  저녁  
..         ...  ..  
239     20.39%  저녁  
240      7.36%  저녁  
241      8.82%  저녁  
242      9.82%  저녁  
243     15.97%  저녁  

[244 rows x 10 columns]

In [194]:
df_tips.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [195]:
df_tips.시간대.value_counts()

시간대
저녁    176
점심     68
Name: count, dtype: int64

## 그룹으로 묶기

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

In [196]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data1': [1, 2, 3, 1, 2, 3],
    'data2':np.random.randint(0, 6, 6)
    }
                  )

In [197]:
df

key  data1  data2
0   A      1      1
1   B      2      2
2   C      3      2
3   A      1      2
4   B      2      2
5   C      3      4

In [198]:
df.groupby('key')

In [199]:
df.groupby('key').sum()

data1  data2
key              
A        2      3
B        4      4
C        6      6

In [200]:
df.groupby(['key','data1']).sum()

data2
key data1       
A   1          3
B   2          4
C   3          6

In [201]:
df.groupby('key').aggregate(['min', 'median', 'max', 'mean'])

data1                 data2                
      min median max mean   min median max mean
key                                            
A       1    1.0   1  1.0     1    1.5   2  1.5
B       2    2.0   2  2.0     2    2.0   2  2.0
C       3    3.0   3  3.0     2    3.0   4  3.0

In [202]:
df.groupby('key').aggregate({'data1': 'min', 'data2': 'sum'})

data1  data2
key              
A        1      3
B        2      4
C        3      6

In [203]:
df.groupby('key').apply(lambda x: x.max() - x.min())

data1  data2
key              
A        0      1
B        0      0
C        0      2

### 연습

문제. 제품별로 평균 가격과 최대가격을 출력하세요

In [204]:
# 직접해보세요
table2 = {
    '일자':['2021-12-06','2021-12-07','2021-12-08','2021-12-09'],
    '가격':[1000,3000,2000,1000],
    '구매여부':[False, True, True, True],
    '제품': ['gum','snack','beverage','gum']
}

df = pd.DataFrame(table2)
df


일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

In [205]:
#@title
df.groupby('제품')['가격'].agg(['mean', 'max'])

mean   max
제품                    
beverage  2000.0  2000
gum       1000.0  1000
snack     3000.0  3000

In [206]:
df_tips

total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

    percentage 시간대  
0        5.94%  저녁  
1       16.05%  저녁  
2       16.66%  저녁  
3       13.98%  저녁  
4       14.68%  저녁  
..         ...  ..  
239     20.39%  저녁  
240      7.36%  저녁  
241      8.82%  저녁  
242      9.82%  저녁  
243     15.97%  저녁  

[244 rows x 10 columns]

문제. 성별로 tip의 평균을 구하세요

In [207]:
# 직접 풀어보세요

df_tips.groupby(['sex'])[['tip']].mean()

/tmp/ipython-input-676436855.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex'])[['tip']].mean()


tip
sex             
Male    3.089618
Female  2.833448

In [208]:
#@title
df_tips.groupby('sex')[['tip']].mean()

/tmp/ipython-input-171013107.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby('sex')[['tip']].mean()


tip
sex             
Male    3.089618
Female  2.833448

In [209]:
#@title
df_tips.groupby("sex").agg({"tip": np.mean})

/tmp/ipython-input-3747278555.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby("sex").agg({"tip": np.mean})
/tmp/ipython-input-3747278555.py:2: FutureWarning: The provided callable <function mean at 0x7c077f94c220> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_tips.groupby("sex").agg({"tip": np.mean})


tip
sex             
Male    3.089618
Female  2.833448

문제. day와 time 별로 total_bill의 최대, 최소, 중간값, 평균을 구하세요

In [210]:
# 직접 풀어보세요

df_tips.groupby(['day','time'])['total_bill'].aggregate(['max', 'min', 'median', 'mean'])

/tmp/ipython-input-3755421993.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['day','time'])['total_bill'].aggregate(['max', 'min', 'median', 'mean'])


max    min  median       mean
day  time                                   
Thur Lunch   43.11   7.51  16.000  17.664754
     Dinner  18.78  18.78  18.780  18.780000
Fri  Lunch   16.27   8.58  13.420  12.845714
     Dinner  40.17   5.75  18.665  19.663333
Sat  Lunch     NaN    NaN     NaN        NaN
     Dinner  50.81   3.07  18.240  20.441379
Sun  Lunch     NaN    NaN     NaN        NaN
     Dinner  48.17   7.25  19.630  21.410000

In [211]:
#@title
df_tips.groupby(['day', 'time']).agg(['max', 'min', 'median', 'mean'])[['total_bill']]

/tmp/ipython-input-150650890.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['day', 'time']).agg(['max', 'min', 'median', 'mean'])[['total_bill']]


TypeError: Cannot perform max with non-ordered Categorical

describe도 가능합니다!

In [212]:
df_tips.groupby(['day', 'time'])['total_bill'].describe()

/tmp/ipython-input-3355838761.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['day', 'time'])['total_bill'].describe()


count       mean       std    min      25%     50%      75%  \
day  time                                                                  
Thur Lunch    61.0  17.664754  7.950334   7.51  12.4300  16.000  20.2700   
     Dinner    1.0  18.780000       NaN  18.78  18.7800  18.780  18.7800   
Fri  Lunch     7.0  12.845714  2.842228   8.58  11.1250  13.420  14.7000   
     Dinner   12.0  19.663333  9.471753   5.75  12.3525  18.665  23.8825   
Sat  Dinner   87.0  20.441379  9.480419   3.07  13.9050  18.240  24.7400   
Sun  Dinner   76.0  21.410000  8.832122   7.25  14.9875  19.630  25.5975   

               max  
day  time           
Thur Lunch   43.11  
     Dinner  18.78  
Fri  Lunch   16.27  
     Dinner  40.17  
Sat  Dinner  50.81  
Sun  Dinner  48.17

In [213]:
#@title
df_tips.groupby(['day', 'time'])['total_bill'].describe()

/tmp/ipython-input-2183882280.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['day', 'time'])['total_bill'].describe()


count       mean       std    min      25%     50%      75%  \
day  time                                                                  
Thur Lunch    61.0  17.664754  7.950334   7.51  12.4300  16.000  20.2700   
     Dinner    1.0  18.780000       NaN  18.78  18.7800  18.780  18.7800   
Fri  Lunch     7.0  12.845714  2.842228   8.58  11.1250  13.420  14.7000   
     Dinner   12.0  19.663333  9.471753   5.75  12.3525  18.665  23.8825   
Sat  Dinner   87.0  20.441379  9.480419   3.07  13.9050  18.240  24.7400   
Sun  Dinner   76.0  21.410000  8.832122   7.25  14.9875  19.630  25.5975   

               max  
day  time           
Thur Lunch   43.11  
     Dinner  18.78  
Fri  Lunch   16.27  
     Dinner  40.17  
Sat  Dinner  50.81  
Sun  Dinner  48.17

문제 성별과 흡연유무로 나누어 데이터의 갯수를 출력하세요

In [214]:
# 직접 풀어보세요

pd.Series([1, 2, 3, np.nan]).count()

np.int64(3)

In [215]:
pd.Series([1, 2, 3, np.nan]).size

4

In [216]:
#@title
df_tips.groupby(['sex', 'smoker']).size()

/tmp/ipython-input-3711849052.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex', 'smoker']).size()


sex     smoker
Male    Yes       60
        No        97
Female  Yes       33
        No        54
dtype: int64

In [217]:
df_tips.groupby(['sex', 'smoker']).count()

/tmp/ipython-input-1062872237.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex', 'smoker']).count()


total_bill  tip  day  time  size  bill_per_size  percentage  \
sex    smoker                                                                
Male   Yes             60   60   60    60    60             60          60   
       No              97   97   97    97    97             97          97   
Female Yes             33   33   33    33    33             33          33   
       No              54   54   54    54    54             54          54   

               시간대  
sex    smoker       
Male   Yes      60  
       No       97  
Female Yes      33  
       No       54

문제. 성별과 흡연유무 별로 평균 팁 비율을 `팁비율 : 00%` 형식으로 출력하세요

In [218]:
# 직접 풀어보세요

df_tips['percentage'] = df_tips.tip / df_tips.total_bill


df_tips


total_bill   tip     sex smoker   day    time  size  bill_per_size  \
0         16.99  1.01  Female     No   Sun  Dinner     2       8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3       3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3       7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2      11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4       6.147500   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2       8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2       9.390000   

     percentage 시간대  
0      0.059447  저녁  
1      0.160542  저녁  
2      0.166587  저녁  
3      0.139780  저녁  
4      0.146808  저녁  
..          ...  ..  
239    0.203927  저녁  
240    0.073584  저녁  
241    0.088222  저녁  
242    0.098204  저녁  
243    0.159744  저녁  

[244 rows x 10 columns]

In [220]:
df_tips.groupby(['sex','smoker']).apply(lambda x: np.mean(x.percentage))

/tmp/ipython-input-4274378499.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex','smoker']).apply(lambda x: np.mean(x.percentage))
/tmp/ipython-input-4274378499.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_tips.groupby(['sex','smoker']).apply(lambda x: np.mean(x.percentage))


sex     smoker
Male    Yes       0.152771
        No        0.160669
Female  Yes       0.182150
        No        0.156921
dtype: float64

In [221]:
#@title
df_tips.groupby(['sex','smoker']).apply(lambda x: f'{np.mean(x.percentage*100):.0f}%')

/tmp/ipython-input-1990472899.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex','smoker']).apply(lambda x: f'{np.mean(x.percentage*100):.0f}%')
/tmp/ipython-input-1990472899.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_tips.groupby(['sex','smoker']).apply(lambda x: f'{np.mean(x.percentage*100):.0f}%')


sex     smoker
Male    Yes       15%
        No        16%
Female  Yes       18%
        No        16%
dtype: object

In [222]:
#@title
df_tips.groupby(['sex', 'smoker']).mean()['percentage'].apply(lambda x : f'{round(x)} %')

/tmp/ipython-input-527265236.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex', 'smoker']).mean()['percentage'].apply(lambda x : f'{round(x)} %')


TypeError: category dtype does not support aggregation 'mean'

In [223]:
df_tips.groupby(['sex', 'smoker']).mean()[['percentage']].astype(str)

/tmp/ipython-input-3023015443.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tips.groupby(['sex', 'smoker']).mean()[['percentage']].astype(str)


TypeError: category dtype does not support aggregation 'mean'

## MultiIndex & pivot_table

In [224]:
df = pd.DataFrame(
np.random.randn(4, 2),
index=[['A', 'A', 'B', 'B'], [1, 2, 1, 2]],
columns=['data1', 'data2']
)

In [225]:
df

data1     data2
A 1 -1.276595  0.479426
  2 -0.682937  0.473708
B 1 -0.060388  0.898478
  2  0.636463 -0.492351

In [226]:
df = pd.DataFrame(
np.random.randn(4, 4),
columns=[["A", "A", "B", "B"], ["1", "2", "1", "2"]])
df

A                   B          
          1         2         1         2
0 -0.952693 -0.926476  1.279040  0.329544
1 -1.989802  1.537097 -0.426811  0.470309
2  0.907512  0.427618 -0.000852  0.007025
3  0.000641  1.274847  2.651670 -0.509277

다중 인덱스 컬럼의 경우 인덱싱은 계층적으로 한다.  
인덱스 탐색의 경우에는 loc, iloc를 사용가능하다

In [227]:
df['A']

1         2
0 -0.952693 -0.926476
1 -1.989802  1.537097
2  0.907512  0.427618
3  0.000641  1.274847

In [229]:
df["A"]["1"]

0   -0.952693
1   -1.989802
2    0.907512
3    0.000641
Name: 1, dtype: float64

Pivot Table

데이터에서 필요한 자료만 뽑아서 새롭게 요약,분석 할 수 있는 기능.     
엑셀에서의 피봇 테이블과 같다
-  Index : 행 인덱스로 들어갈 key
- Column : 열 인덱스로 라벨링될 값
- Value : 분석할 데이터

In [230]:
# 딕셔너리 형태로 데이터프레임 만들기
table2 = {
    '일자':['2021-12-06','2021-12-07','2021-12-08','2021-12-09','2021-12-06','2021-12-07','2021-12-08','2021-12-09'],
    '가격':[1000,3000,2000,1000, 1000,3000,2000,1000],
    '구매여부':['False','True','True','True', 'False','True','True','True'],
    '제품': ['gum','snack','beverage','gum', 'gum','snack','beverage','gum']
}

df2 = pd.DataFrame(table2)
df2

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum
4  2021-12-06  1000  False       gum
5  2021-12-07  3000   True     snack
6  2021-12-08  2000   True  beverage
7  2021-12-09  1000   True       gum

In [231]:
df2.pivot_table(
index='구매여부', columns='제품', values='가격', aggfunc="mean"
)

제품     beverage     gum   snack
구매여부                           
False       NaN  1000.0     NaN
True     2000.0  1000.0  3000.0

문제. 성별과 흡연유무 별로 평균 팁 비율을 피봇테이블로 출력하세요

In [ ]:
# 직접 풀어보세요



In [232]:
#@title
df_tips.pivot_table(index = 'sex', columns = 'smoker', values = 'percentage', aggfunc="mean")

/tmp/ipython-input-3683003348.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_tips.pivot_table(index = 'sex', columns = 'smoker', values = 'percentage', aggfunc="mean")


smoker       Yes        No
sex                       
Male    0.152771  0.160669
Female  0.182150  0.156921

In [233]:
#@title
data = df_tips.pivot_table(index = 'sex', columns = 'smoker', values = 'percentage',
                           aggfunc=lambda x: f'{round(np.mean(x))}%')
data

/tmp/ipython-input-1273766787.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  data = df_tips.pivot_table(index = 'sex', columns = 'smoker', values = 'percentage',


smoker Yes  No
sex           
Male    0%  0%
Female  0%  0%